{
 "title": "Application / Frontend / Faro",
 "description": "Frontend monitoring dashboard using metrics collected with Grafana Faro SDK.",
 "tags": [
  "Logs",
  "Frontend",
  "Faro",
  "Grafana"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "app",
    "label": "App",
    "query": {}
   },
   {
    "name": "version",
    "label": "Version",
    "query": {}
   },
   { "name": "Log", "label": "Log", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "stat",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(ttfb[$__range])" }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "stat",
   "description": "The First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.\nhttps://web.dev/fcp/",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(fcp[$__range])" }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "stat",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(cls[$__range])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "stat",
   "description": "Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.\nhttps://web.dev/lcp/",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(lcp[$__range])" }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "stat",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(fid[$__range])" }
   ]
  },
  {
   "title": "INP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(inp[$__range])" }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, fcp[5m])",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, lcp [5m])  ",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    { "expr": "avg_over_time(cls[$__range])" }
   ]
  },
  {
   "title": "Interactivity, p75",
   "type": "timeseries",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, fid[5m]) ",
     "legendFormat": "FID"
    },
    {
     "expr": "quantile_over_time(0.75, inp[5m])",
     "legendFormat": "INP"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({\n    kind=\"exception\",\n    app=\"$app\",\n    version=~\"$version\"\n} [$__range])) by (app)"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "count_over_time({\n    kind=\"exception\",\n    app=\"$app\",\n    version=~\"$version\"\n} [$__interval])",
     "legendFormat": "errors"
    },
    { "type": "math" }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({\n    kind=\"exception\",\n    app=\"$app\",\n    version=~\"$version\"\n} | logfmt [$__range])) by (value))"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({\n    kind=\"measurement\",\n    app=\"$app\",\n    verion=~\"$version\"\n} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, \n    count by (\n        browser_name,\n        browser_version\n    ) (\n    count_over_time({\n        kind=\"measurement\",\n        app=\"$app\",\n        version=~\"$version\"\n    } | logfmt [$__range]))\n)"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, count(\n    count_over_time({\n        kind=\"measurement\",\n        app=\"$app\",\n        version=~\"$version\"\n    }  | logfmt [$__range])\n) by (browser_name, browser_version))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "count_over_time({\n    kind=\"measurement\",\n    app=\"$app\",\n    version=~\"$version\"\n} |= \" ttfb=\" [$__interval])",
     "legendFormat": "visits"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({\n    kind=\"event\",\n    app=\"$app\",\n    version=~\"$version\"\n} | logfmt [$__range])) by (event_name))"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "topk(50, count(count_over_time({\n    kind=\"measurement\",\n    app=\"$app\",\n    version=~\"$version\"\n} | logfmt [$__range])) by (session_id, browser_name, browser_os))"
    }
   ]
  }
 ]
}