apiVersion: 1
contactPoints:
  - orgId: 1
    name: admin
    receivers:
      - uid: deaakkjrkdipta
        type: email
        settings:
          addresses: admin@optiop.org
          singleEmail: false
        disableResolveMessage: false
