services:
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/tempo-data:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  alloy:
    image: grafana/alloy:v1.19.2
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4319:4319"
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:11.6.6
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_LOG_LEVEL: critical
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
      GF_SECURITY_ALLOW_EMBEDDING: true
    ports:
      - "3000:3000"
  # Generate fake traces...

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
    environment:
      - ENDPOINT=alloy:4317
    restart: always
    depends_on:
      - tempo
      - alloy
