global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: us1
    replica: 1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-0-us1:9091', 'prometheus-1-us1:9092']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['prometheus-0-sidecar-us1:19091', 'prometheus-1-sidecar-us1:19092']