---
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    user: root
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=1000d'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.min-block-duration=2h'
      - '--web.listen-address=:9090'
      - '--web.external-url=http://localhost:9090'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  thanos-sidecar:
    image: thanosio/thanos:v0.37.2
    container_name: thanos-sidecar
    restart: unless-stopped
    user: root
    volumes:
      - ./thanos/bucket_storage.yaml:/etc/thanos/minio-bucket.yaml
    command:
      - sidecar
      - --objstore.config-file=/etc/thanos/minio-bucket.yaml
      - --shipper.upload-compacted 
      - --http-address=0.0.0.0:19090
      - --grpc-address=0.0.0.0:19190
      - --prometheus.url=http://prometheus:9090

  thanos-querier:
    image: thanosio/thanos:v0.37.2
    container_name: thanos-querier
    restart: unless-stopped
    ports:
      - 9091:9091
    command:
      - query
      - --http-address=0.0.0.0:9091
      - --query.replica-label=replica
      - --store=thanos-sidecar:19190
      - --store=thanos-gateway:19191

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 35549:35549
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=melovethanos
    command: server /data --console-address ":35549"


  thanos-gateway:
    image: thanosio/thanos:v0.37.2
    container_name: thanos-gateway
    restart: unless-stopped
    user: root
    volumes:
      - ./thanos/bucket_storage.yaml:/etc/thanos/minio-bucket.yaml
    command:
      - store
      - --objstore.config-file=/etc/thanos/minio-bucket.yaml
      - --http-address=0.0.0.0:19091
      - --grpc-address=0.0.0.0:19191