route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'pre-prod-slack-channel'

  routes:
    - match:
        environment: 'prod'
      receiver: 'prod-slack-channel'
      
    - receiver: 'pre-prod-slack-channel'

receivers:
  - name: 'prod-slack-channel'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/'
        channel: '#prod-alerts'
        send_resolved: true

  - name: 'pre-prod-slack-channel'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/'
        channel: '#pre-prod-alerts'
        send_resolved: true
