groups:
  - name: should_fire
    rules:
      - alert: HighPercentageError
        expr: 1 > 0.05
        for: 0s
        labels:
          severity: critical
          environment: prod
        annotations:
          summary: High request latency

      - alert: HighRAMUsageError
        expr: 1 > 0.05
        for: 0s
        labels:
          severity: page
        annotations:
          summary: High request latency