---
services:
  # And put them in a Grafana Alloy pipeline...
  alloy:
    image: grafana/alloy:v1.19.2
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4319:4319"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    depends_on:
      - minio

  grafana:
    image: grafana/grafana:11.6.6
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_RECORDING_RULES_ENABLED=true
      - GF_RECORDING_RULES_URL=http://loki:3100/loki/api/v1/push
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        chmod -R 777 /data && \
        minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
