apiVersion: 1

datasources:
  - name: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Mimir
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m