deploymentMode: SingleBinary

loki:
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin
  schemaConfig:
    configs:
      - from: "2020-05-15"
        store: "tsdb"
        objectStore: "filesystem"
        schema: "v13"
        index:
          prefix: "index_"
          period: "24h"
  auth_enabled: false

gateway:
  service:
    enabled: true
    type: ClusterIP
    port: 80

chunksCache:
  enabled: false

backend:
  replicas: 0
write:
  replicas: 0
read:
  replicas: 0