services:
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo/data:/var/tempo

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
    depends_on:
      - init
    networks:
      - app-network

  backend:
    build:
      context: ./steam-service
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

  alloy:
    # Grafana Alloy version 1.5.1
    # https://hub.docker.com/r/grafana/alloy/tags
    image: grafana/alloy:v1.5.1
    privileged: true
    ports:
      - 12345:12345
      - 4319:4319
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    networks:
      - app-network
  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:11.4.0
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_LOG_LEVEL: critical
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
      GF_SECURITY_ALLOW_EMBEDDING: true
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
