[server]
# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false


[security]
# disable creation of admin user on first start of grafana
;disable_initial_admin_creation = false

# default admin user, created on startup
admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
admin_password = admin
cookie_samesite = lax
cookie_secure = false
strict_transport_security = false


[users]

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Set this value to automatically add new users to the provided organization (if auto_assign_org above is set to true)
auto_assign_org_id = 1

# Default role new users will be automatically assigned
auto_assign_org_role = Viewer

# Require email validation before sign up completes
verify_email_enabled = false

# Default UI theme ("dark", "light" or "system")
default_theme = dark

# Default UI language (supported IETF language tag, such as en-US)
default_language = en-US


[auth]

# Use email lookup in addition to the unique ID provided by the IdP
oauth_allow_insecure_email_lookup = false



[auth.generic_oauth]
enabled = true
name = Keycloak
allow_sign_up = true
client_id = dashboard
client_secret = cwrCP1uLwxo2IZSFewg1BTf3BgiUsZQp
scopes = openid email profile offline_access roles
email_attribute_path = email
auth_url = http://localhost:8080/realms/imbue-sustainability/protocol/openid-connect/auth
token_url = http://keycloak:8080/realms/imbue-sustainability/protocol/openid-connect/token
api_url = http://localhost:8080/realms/imbue-sustainability/protocol/openid-connect/userinfo
role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'