apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  type: ClusterIP
  selector:
    app: java-app
  ports:
    - port: 8081
      targetPort: 8081
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: java-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: "simple-java-app"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4318"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          ports:
            - containerPort: 8081