datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.loki
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: "xurupita"
        access: proxy
        isDefault: true
        editable: true

service:
  enabled: true
  type: ClusterIP
  port: 3000
  targetPort: 3000
 