---
services:
  # And put them in a Grafana Alloy pipeline...
  alloy:
    image: grafana/alloy:v1.5.1
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4319:4319"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/rules/rules.yml:/etc/loki/rules/fake/rules.yml

  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_RECORDING_RULES_ENABLED=true
      - GF_RECORDING_RULES_URL=http://loki:3100/loki/api/v1/push
    ports:
      - "3000:3000"
