alloy:
  configMap:
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.kubernetes "nodes" {
        role = "node"
      }

      discovery.kubernetes "services" {
        role = "service"
      }

      discovery.kubernetes "endpoints" {
        role = "endpoints"
      }

      discovery.kubernetes "endpointslices" {
        role = "endpointslice"
      }

      discovery.kubernetes "ingresses" {
        role = "ingress"
      }

      prometheus.exporter.unix "nodeexporter" {
      }

      prometheus.scrape "nodeexporter" {
        job_name = "node-exporter"
        targets  = prometheus.exporter.unix.nodeexporter.targets
        scheme   = "http"
        forward_to = [prometheus.remote_write.cloud.receiver]
      }

      prometheus.exporter.cadvisor "cadvisor" {
      }

      prometheus.scrape "cadvisor" {
        job_name = "cadvisor"
        targets  = prometheus.exporter.cadvisor.cadvisor.targets
        scheme = "https"
        forward_to = [prometheus.remote_write.cloud.receiver]
      }

      discovery.kubernetes "k8s_pods" {
        role = "pod"
        api_server = "https://kubernetes.default.svc.cluster.local"
      }

      prometheus.scrape "kube_api_server" {
        job_name = "kube_api_server"
        targets  = discovery.kubernetes.k8s_pods.targets
        scheme   = "https"
        forward_to = [prometheus.remote_write.cloud.receiver]
      }

      discovery.kubelet "kubelet" {
      }

      prometheus.scrape "kubelet" {
        job_name = "kubelet"
        targets  = discovery.kubelet.kubelet.targets
        scheme   = "https"
        forward_to = [prometheus.remote_write.cloud.receiver]
      }

      prometheus.remote_write "cloud" {
        endpoint {
          name = "hosted-prometheus"
          url  = "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
          basic_auth {
            username = ""
            password = ""
          }
        }
      }