apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    server:
      http_listen_port: 9009

    distributor: {}

    ingester:
      ring:
        kvstore:
          store: inmemory

    limits:
      max_global_series_per_user: 10000000
    